### ISSUE TITLE
使用 gulp 命令构建时会报 undefined 错误

### ISSUE THREAD

**Issue by BigKongfuPanda** [holyzfy/febu#65]
安装完依赖之后，在 febu 目录下 运行 gulp 构建命令，如：

> gulp development --repo http://gitlab.tcredit.com/f2e/api.git  --publicPath /static/

会报出以下的错误：

> can't read property 'apply' of undefined

解决办法是在全局安装了 gulp 之后，再运行以下命令:

> sudo npm i gulp-cli -g

这样问题就解决了。

**Comment by holyzfy** [comment]
`npm install`时会全局安装`gulp-cli`的
https://github.com/holyzfy/febu/blob/3b440a5ec0091c2fe0b01fc1c13d7bb9ef04b196/package.json#L20

建议把npm配置成免sudo安装全局模块 https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by BigKongfuPanda** [comment]
哦。看起来权限的原因。
