### ISSUE TITLE
可否增加直接指定本地文件夹进行构建的特性

### ISSUE THREAD

**Issue by windsummer** [holyzfy/febu#75]
构建时每次都需要请求git获取最新代码，在网速较慢的情况下，每次构建获取前获取git代码都要花费比较多的时间，可否增加直接指定本地文件夹进行构建的特性？

**Comment by holyzfy** [comment]
第一次是`git clone`操作，花费时间较长；后续再发版时是`git pull`操作，增量进行的，`git pull`操作很快。

目前febu不支持自定义指定输入文件夹，可以fork后自行实现，例如增加输入参数`src`表示指定本地文件夹，因为`src`目录格式不清楚，建议使用`src`的时候要求必须指定`dist`参数，这时候请忽略参数`repo`，`branch `，`commit`，因为此时这些参数已无意义。

需要重写的相关代码：

- **gulpfile.js**: [gulp.task('before', done => {...}](https://github.com/holyzfy/febu/blob/master/gulpfile.js#L26)
- **module/common.js**: [common.getCwd(repo, type)](https://github.com/holyzfy/febu/blob/master/module/common.js#L19)
